### ISSUE TITLE
Enter set 1 data for all 15 weeks

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#16]

**Comment by kitchen-ace** [comment]
I'm tentatively planning on doing this Monday.

**Comment by kitchen-ace** [comment]
The challenge details have all been entered.

Scores haven't been, because (I need a break, but also) the format was different for set 1, with a perfect score being *70* points. I am debating whether I want to retrofit the past scores into a 50 point system or leave them as-is. I am leaning towards the former; if people want to submit very late scores for old entries I would like them to be able to, and it makes sense to use the current scoring system.

(Set 2 also uses a different format but it's compatible with the current scoring system, so no need to do anything there.)

**Comment by alkemann** [comment]
I guess with #47 this is no longer valid and should be closed?
