### ISSUE TITLE
Bug for top score for set 4

### ISSUE THREAD

**Issue by RoGGa-loves-DCSS** [alkemann/stone_soup_cosplay#57]
see Blorx1's score for set 4: it doesn't add up
My guess there's a double entry that is counted also
see: http://www.crawlcosplay.com/sets/score?set=4

**Comment by alkemann** [comment]
There are two "Accepted" and "Highscore" runs for the same challenge. The one without the star needs to lose it's "HS" tag.
<img width="606" alt="Screenshot 2019-04-25 at 16 20 42" src="https://user-images.githubusercontent.com/48854/56743118-443a8b00-6776-11e9-876e-ee303e270485.png">

**Comment by RoGGa-loves-DCSS** [comment]
I'll reassign to kitchen_ace:
this might happen often when multiple people are doing entries.
Do you want additional fields ...like:
timestamp, entered by admin (or via Submit a Run)

**Comment by alkemann** [comment]
We can have a code check that removes the "high score" from previous entries when a new one is submitted? But if they are for the same score, should we not assume that it is a duplicate instead of a new run with same results. Not a lot of value in registering multiple runs with the same score is it?
